= Configure a Camel component using CDI: A Camel Quarkus example
:cq-example-description: An example that demonstrates how to set-up a Camel component (the `log` component in this case) programmatically using CDI

{cq-description}

TIP: Check the https://camel.apache.org/camel-quarkus/latest/first-steps.html[Camel Quarkus User guide] for prerequisites
and other general information.

== Start in the Development mode

[source,shell]
----
$ mvn clean compile quarkus:dev
----

The above command compiles the project, starts the application and lets the Quarkus tooling watch for changes in your
workspace. Any modifications in your project will automatically take effect in the running application.

TIP: Please refer to the Development mode section of
https://camel.apache.org/camel-quarkus/latest/first-steps.html#_development_mode[Camel Quarkus User guide] for more details.

Then look at the log output in the console. As we run the example in Quarkus Dev Mode, you can edit the source code and have live updates.
For example try to change `Incremented the counter` to `Counter state` in the message body or change the property `timer.period` in application.properties

=== Package and run the application

Once you are done with developing you may want to package and run the application.

TIP: Find more details about the JVM mode and Native mode in the Package and run section of
https://camel.apache.org/camel-quarkus/latest/first-steps.html#_package_and_run_the_application[Camel Quarkus User guide]

==== JVM mode

[source,shell]
----
$ mvn clean package
$ java -jar target/quarkus-app/quarkus-run.jar
...
[io.quarkus] (main) camel-quarkus-examples-... started in 1.163s.
----

==== Native mode

IMPORTANT: Native mode requires having GraalVM and other tools installed. Please check the Prerequisites section
of https://camel.apache.org/camel-quarkus/latest/first-steps.html#_prerequisites[Camel Quarkus User guide].

To prepare a native executable using GraalVM, run the following command:

[source,shell]
----
$ mvn clean package -Pnative
$ ./target/*-runner
...
[io.quarkus] (main) camel-quarkus-examples-... started in 0.013s.
...
----

==== Testing it locally

To test using `curl` set the `http_proxy` environment variable, for example:

    $ http_proxy=http://localhost:8000 curl -v http://echo-api.3scale.net

==== Registry operator

Deploy Postgres Database

    username: postgres
    pass: abc123
    database: registry

Install Registry Operator

    apiVersion: apicur.io/v1alpha1
    kind: ApicurioRegistry
    metadata:
    name: example-apicurioregistry
    spec:
    configuration:
        persistence: "jpa"
        dataSource:
        url: "jdbc:postgresql://postgresql.demo.svc:5432/registry"
        userName: "postgres"
        password: "abc123"

==== 3Scale 

    docker run -it -p 8081:8080 -e THREESCALE_PORTAL_ENDPOINT=https://TOKEN@3scale-admin.apps.cluster-5f88.5f88.sandbox1482.opentlc.com registry.access.redhat.com/3scale-amp20/apicast-gateway:1.0

    docker run -it -p 8081:8080 -e APICAST_CONFIGURATION_LOADER=lazy -e APICAST_LOG_LEVEL=debug  -e THREESCALE_PORTAL_ENDPOINT=https://241559203ce29b7ce334ae470d65ece22a91b70ef4ccfa4d7345f29c03e1c9a6@3scale-admin.apps.cluster-5f88.5f88.sandbox1482.opentlc.com registry.access.redhat.com/3scale-amp20/apicast-gateway:1.0

== Feedback

Please report bugs and propose improvements via https://github.com/apache/camel-quarkus/issues[GitHub issues of Camel Quarkus] project.
