apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: person
spec:
  name: "person"
  deployment:
    apicastHosted: {}
  backendUsages:
    publicbanks:
      path: /public
  applicationPlans:
    production:
      name: "production"
    sandbox:
      name: "sandbox"
      trialPeriod: 7
      costMonth: "5"
      limits:
        - period: week
          value: 100
          metricMethodRef:
            systemName: hits
      pricingRules:
        - from: 1
          to: 100
          pricePerUnit: "0.10"
          metricMethodRef:
            systemName: hits